### PR TITLE
Add Resources

### PR DESCRIPTION
**Pull request by scott-grimes**
allow configuration of the operators resources

### CODE REVIEW

**Comment by DeyvsonL** [comment]
Do we have any expectations about when this will be merged?

**Comment by tkp75** [comment]
Shouldn't the manager-upgrade.yaml have resources support too?

**Comment by benjaminjb** [comment]
Could you 
(a) rebase off `devel`
(b) PR this to merge into `devel`
(c) and add resources to the manager-upgrade.yaml as well? (thanks for pointing that out @tkp75 )

**Comment by scott-grimes** [comment]
done. feel free to edit further if needed

**Comment by benjaminjb** [comment]
Tested and made some slight changes, thanks for the PR -- can you deploy with Helm with these changes?

**Review by benjaminjb — APPROVED** [review]

**Pull request merged**
