### PR TITLE
feat: Add customised env var and feature flags

### LINKED ISSUE #262: Add feature gate support to helm chart
It would be really nice if the Helm chart supported feature gates. Currently, there is no way to inject a custom env value into the chart manifest so feature gates are essentially non-operable.

### PR DESCRIPTION
**Pull request by jaitaiwan**
This change adds 3 new features:
 - The ability to enable feature flags with the .Values.features key
 - The ability to add extra environment variables to the container env
 - The ability to completely override env variables (not recommended)

Closes #262

### CODE REVIEW

**Comment by eliaoggian** [comment]
+1

**Comment by andrewlecuyer** [comment]
Hi @jaitaiwan, thanks for the submission!  I'm currently reviewing your changes, which look great.

However, one thing that needs to be considered is _disabling_ a feature gate.  In other words, right now your changes allow users to set certain feature gates to `true`, but it might also be necessary to set a feature flag to `false`.

Therefore, do you have any thoughts regarding a solution to allow users to both enable and disable feature gates?  Addressing that concern should pave the way for getting this PR merged.

**Comment by jaitaiwan** [comment]
I can make a change for that, I’ll add another commit!

**Comment by jaitaiwan** [comment]
Hey @andrewlecuyer I've gone ahead and updated the PR. Now the `.Values.features` allows you to specify either a slice of values to set to `true` or you can specify a `map[string]string` where the key is the feature name and the value is the value to be passed in to the flag. This should make it future proof if you go beyond the concept of a flag. I've put the examples in the values file but let me be explicit here.

The following values file:
```
features:
  - AutoGrow
  - AnotherFeature
  - YetAnotherFeature
```

Results in the following env var:
```
- name: PGO_FEATURE_GATES
  value: "AutoGrow=true,AnotherFeature=true,YetAnotherFeature=true"
```

So assuming we want say `AnotherFeature` to be `false` and even provide an arbitrary string to `YetAnotherFeature` we can then do:
```
features:
  AutoGrow: true
  AnotherFeature: false
  YetAnotherFeature: myarbitrarystring
```

Results in:
```
- name: PGO_FEATURE_GATES
  value: "AutoGrow=true,AnotherFeature=false,YetAnotherFeature=myarbitrarystring"
```

Hopefully this fits the bill?

**Comment by jshimko** [comment]
Great work @jaitaiwan!  Anything else preventing merging this @andrewlecuyer?  I could really use this for our PGO installation as well.  We were really excited to use the new [automatic per-user schema creation](https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/basic-setup/user-management#automatically-creating-per-user-schemas), but we had to manually patch the PGO deployment env with `PGO_FEATURE_GATES="AutoCreateUserSchema=true"` to make it work.  Obviously an easy enough workaround to get things working with the chart, but we try to manage everything in our cluster with ArgoCD/gitops so manual patching is a big no-no for us.  But then I found this PR and have just been working from this fork in the meantime.  Would love to get this merged to make it official if possible!  Cheers!

**Comment by ValClarkson** [comment]
Thanks for the PR and the last update! I think we should move forward with supporting this approach:
```
features:
  AutoGrow: true
  AnotherFeature: false
  YetAnotherFeature: myarbitrarystring
```
Could you remove the support for the this style?
```
features:
  - AutoGrow
  - AnotherFeature
  - YetAnotherFeature
```
This change aligns with our upcoming feature gate, which will have its first feature set to
true by default. We want to encourage users to think in terms of setting values explicitly to true or false, rather than just listing features. Thanks for your understanding!

**Comment by jaitaiwan** [comment]
Okay! I've updated the branch with those requested changes.

**Review by andrewlecuyer — APPROVED** [review]

**Review by ValClarkson — APPROVED** [review]

**Comment by andrewlecuyer** [comment]
Thanks for the contribution @jaitaiwan!

**Pull request merged**
