### PR TITLE
Release helm charts with chart-releaser

### LINKED ISSUE #23: Publish Helm chart
Please publish the Helm chart.

It can be done with [chart-releaser](https://github.com/helm/chart-releaser-action) or [helm-publish](https://github.com/marketplace/actions/helm-publish) Github action, for example.

### PR DESCRIPTION
**Pull request by sathieu**
Fixes #23.

Prerequisites:
- Create a `gh-pages` branch (see [here](https://gist.github.com/ramnathv/2227408))

Result: I've done this in my fork, see:
- the log: https://github.com/sathieu/postgres-operator-examples/runs/3697999445
- the resulting *release*: https://github.com/sathieu/postgres-operator-examples/releases/tag/pgo-0.2.0
- the resulting chart repo: https://github.com/sathieu/postgres-operator-examples/blob/gh-pages/index.yaml

### CODE REVIEW

**Comment by sathieu** [comment]
@jkatz Please review

**Comment by sathieu** [comment]
@jkatz @crunchyjohn @andrewlecuyer Sorry to insist, could you please create a CrunchyData/helm-charts repo and I'll propose a PR to implement all this (charts and chart-releaser, then a PR to update the docs)?

**Comment by jkatz** [comment]
@sathieu We are still evaluating our options for publishing Helm charts. As you may have seen, we've put a lot of work into updating the Helm charts to provide functional equivalence to the Kustomize artifacts. Publication is next on the list.

**Comment by sathieu** [comment]
Thanks @jkatz!

**Comment by samip5** [comment]
This is the major thing keeping from trying this out... :(

**Comment by jkatz** [comment]
> This is the major thing keeping me from trying this out.

I hope that you can at least kick the tires using the [quickstart](https://access.crunchydata.com/documentation/postgres-operator/v5/quickstart/) since it's designed to be fast and easy to take PGO for a spin.

There are a variety of ways to automate updates as well beyond having a Helm chart publisher -- and even from a GitOps perspective, we do regularly push updates to GitHub too, which I know works with tools like ArgoCD for automatic deployments (which I have done so myself).

For the other end of it, as mentioned in https://github.com/CrunchyData/postgres-operator-examples/pull/28#issuecomment-965521476 determining a Helm chart publication strategy is on the list of things that we are going to evaluate.

**Comment by samip5** [comment]
> I hope that you can at least kick the tires using the [quickstart](https://access.crunchydata.com/documentation/postgres-operator/v5/quickstart/) since it's designed to be fast and easy to take PGO for a spin.

I find that to be rather troublesome due to having to fork the repo and keeping it up-to-date myself. This is why it's a show stopper for me.

> There are a variety of ways to automate updates as well beyond having a Helm chart publisher -- and even from a GitOps perspective, we do regularly push updates to GitHub too, which I know works with tools like ArgoCD for automatic deployments (which I have done so myself).

I'm using Flux, and I know that it supports git repositories but helm repos/charts are nicer to use.

**Comment by dimitrigraf** [comment]
@samip5 

I forked the repo while evaluating the operator. Once evaluated we directly referenced `helm/install` in the examples repository in our ArgoCD applicaton with a slight change in the values. Worked well so far. 

The operator is very well documented and I'd really recommend you to try it out.

**Comment by samip5** [comment]
> @samip5 
> 
> I forked the repo while evaluating the operator. Once evaluated we directly referenced `helm/install` in the examples repository in our ArgoCD applicaton with a slight change in the values. Worked well so far. Of course, once helm charts are published by Crunchy Data we are going to make the switch.
> 
> The operator is very well documented and I'd really recommend you to try it out :) 

Doesn't change the fact that there's no arm64 images for any of the used ones. :)

**Comment by torbendury** [comment]
Hello @jkatz, is this still an active topic for Crunchy? We'd like to manage the Helm Chart via Terraform and it is a hassle to let it point to a GitHub repo.

**Comment by lowercase00** [comment]
Hey all. This seems like a fairly old issue, mentioned first in [2018](https://github.com/CrunchyData/postgres-operator/issues/417), then [Jan/2021](https://github.com/CrunchyData/postgres-operator/issues/2231), then [Sep/2021](https://github.com/CrunchyData/postgres-operator-examples/issues/23).  In our specific case, we have a bunch of folders full of manifests for several different resources, having to manually download the chart makes it for a less than ideal experience. There are [charts published in ArtifactHub](https://artifacthub.io/packages/search?ts_query_web=pgo&sort=relevance&page=1). But having three different charts, and none of them "official" also doesn't seem ideal.

Understand the release cycle may not be trivial, but wondering if there's any perspective to this issue. Maybe publishing a "beta" version? Given this is a 4yo issue wondering what the plans moving forward are. Is there anything that the community can do to speed this up? I would be happy to help.

**Comment by torbendury** [comment]
> I would be happy to help.

Second that! Although I was not yet involved in pushing charts to public repositories, I'd be glad to learn and lend a helping hand.

**Comment by sylvainOL** [comment]
Hello, any news?
it's a showstopper on our side also :/

**Comment by andrewlecuyer** [comment]
With the release of [Crunchy Postgres for Kubernetes v5.3.0](https://access.crunchydata.com/documentation/postgres-operator/latest/releases/5.3.0/), we are excited to announce that the Helm chart for installing Crunchy Postgres for Kubernetes is now available via OCI registry.

For example, please see the following commands:

```
$ helm show chart oci://registry.developers.crunchydata.com/crunchydata/pgo
Pulled: registry.developers.crunchydata.com/crunchydata/pgo:5.3.0
Digest: sha256:7f50f74b0bb4fde32348af87cc740b79ed7be965f90002bcb2425e27fb02a9e3
apiVersion: v2
appVersion: 5.3.0
description: Installer for PGO, the open source Postgres Operator from Crunchy Data
name: pgo
type: application
version: 5.3.0

$ helm install pgo oci://registry.developers.crunchydata.com/crunchydata/pgo
Pulled: registry.developers.crunchydata.com/crunchydata/pgo:5.3.0
Digest: sha256:7f50f74b0bb4fde32348af87cc740b79ed7be965f90002bcb2425e27fb02a9e3
...
```

Therefore, with a Helm registry for Crunchy Postgres for Kubernetes now implemented, I am proceeding with closing this PR.

For more information about Helm installation via OCI registry, please see the [Helm installation documentation](https://access.crunchydata.com/documentation/postgres-operator/latest/installation/helm/#installing-directly-from-the-registry).

**Pull request closed without merging**
